version: "3"

dotenv:
  - .env

tasks:
  run:
    cmds:
      - go run .
  tidy:
    cmds:
      - go mod tidy
  compose:
    env:
      ENV: "{{.ENV}}"
    cmds:
      - sudo docker compose --profile $ENV up -d --build
  decompose:
    cmds:
      - sudo docker compose down
  test:
    cmds:
      - go test ./... -v
  vet:
    cmds:
      - go vet ./...
  fix:
    cmds:
      - go fix ./...
  watch:
    cmds:
      - air
  deploy:
    env:
      TF_VAR_PROJECT_ID: "{{.PROJECT_ID}}"
      TF_VAR_TELEGRAM_BOT_API_TOKEN: "{{.TELEGRAM_BOT_API_TOKEN}}"
      TF_VAR_MONGO_URI: "{{.MONGO_URI}}"
      TF_VAR_MONGO_DB: "{{.MONGO_DB}}"
    cmds:
      - tofu apply
  ssh:
    vars:
      NAME:
        sh: tofu show -json | jq --raw-output '.values.root_module.resources[] | select(.name == "vm_instance") | .values.name'
      ZONE:
        sh: tofu show -json | jq --raw-output '.values.root_module.resources[] | select(.name == "vm_instance") | .values.zone'
    cmds:
      - gcloud compute ssh --zone {{.ZONE}} --project {{.PROJECT_ID}} {{.EXTRA_ARGS}} {{.NAME}}
  ssh:deploy:
    cmds:
      - task: ssh
        vars:
          EXTRA_ARGS: --command 'cd ~/workspace/telegram-bot-missile-alert-il/ && git pull --rebase && task compose'
  ssh:logs:
    cmds:
      - task: ssh
        vars:
          EXTRA_ARGS: --command 'sudo docker logs --follow telegram-bot-missile-alert-il-app-1'
