version: "3"

tasks:
  run:
    cmds:
      - go run .
  tidy:
    cmds:
      - go mod tidy
  compose:
    env:
      ENV: "{{.ENV}}"
    cmds:
      - sudo docker compose --profile $ENV up -d --build
  decompose:
    cmds:
      - sudo docker compose down
  test:
    cmds:
      - go test ./... -v
  vet:
    cmds:
      - go vet ./...
  fix:
    cmds:
      - go fix ./...
  watch:
    cmds:
      - air
